# -*- coding: utf-8 -*-
"""train_model

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19OIfXR9BguwUTXgCq4LXLe6nMDrSkv-Z
"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import pandas as pd
import pickle

y_train = pd.read_csv("AMO2/y_train.csv",index_col= "Unnamed: 0")
x_train = pd.read_csv("AMO2/x_train.csv")

dtc=DecisionTreeClassifier(criterion='gini')
dtc.fit(x_train,y_train)

pkl_filename = "AMO2/pickle_model.pkl" 
with open(pkl_filename, 'wb') as file: 
  pickle.dump(dtc, file)